# https://code.visualstudio.com/api/working-with-extensions/continuous-integration

name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - env:
        DISPLAY: ":99.0"
      run: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo ">>> Started xvfb"
    - name: npm install, build, and test
      env:
        DISPLAY: ":99.0"
      run: |
        echo ">>> Install dependencies"
        npm install
        echo ">>> Compile vscode-test"
        npm run compile
        echo ">>> Compiled vscode-test"
        echo ">>> Run sample integration test"
        npm test
